package za.ac.sun.cs.hons.minke.utils;

public class Constants {
	public final static String TEST_URL_BASE = "http://10.0.2.2:5000";
	public final static String URL_BASE = "http://kraken.shop-minke.appspot.com";
	public final static String REQUEST_BASE = "/entityRequestServlet?type=";
	public final static String URL_PREFIX = URL_BASE + REQUEST_BASE;
	public static final String HTTP_TAG = "HTTPUtils";
	public static final String RPC_TAG = "RPCUtils";
	public static final String ENTITY_TAG = "EntityUtils";
	public static final String DIR_TAG = "DirectionsActivity";
	public static final String HOME_TAG = "HomeActivity";
	public static final String BROWSE_TAG = "BrowseActivity";
	public static final String SHOP_TAG = "ShopActivity";
	public static final String STORE_TAG = "StoreActivity";
	public static final String GRAPH_TAG = "GraphActivity";
	public static final String USER_ID = "pieterj";
	public final static String KEY = "5fd0b37cd7dbbb00f97ba6ce92bf5add503d2db5495ad7.42776752";
	public static final int ROUTING_CLOUDMADE = 0;
	public static final int ROUTING_YOURNAVIGATION = 1;
	public static final String DECIMALS = "([1-9][0-9]*)+(\\.[0-9]{1,2}+)?";
	public static final String INTS = "([1-9][0-9]*)";
	public static final String CLIENT = "C";
	public static final String SERVER = "S";
	public static final int SUCCESS = 0;
	public static final int CLIENT_ERROR = 1;
	public static final int SERVER_ERROR = 2;
	public static final int PARSE_ERROR = 3;
	public static final int INPUT_ERROR = 4;
	public static final int LOCATION_ERROR = 5;
	public static final int MAP_ERROR = 6;
	public static final int DB_ERROR = 7;
	public static final int NOT_LOADED_ERROR = 8;
	public static final boolean EMULATOR = true;
	public static final boolean GOOGLE_MAPS = true;
	public static final String EMULATOR_KEY = "0TkWntAlV0iBGVtYwpBCtoTg0fnuESyzoWnBjsg";
	public static final String APPLICATION_KEY = "0TkWntAlV0iAoUcY6-k3tkcMPE48tjyGkM9qVWA";
	public static final int NO_FREQUENCY_SET = -1;
	public static final int STARTUP = 0;
	public static final int HOURLY = 1;
	public static final int DAILY = 2;
	public static final int WEEKLY = 3;
	public static final int NEVER = 4;
	public static final long HOUR = 3600000;
	public static final long DAY = 86400000;
	public static final long WEEK = 604800000;
	public static final String DATABASE_NAME = "minke.db";
	public static final int DATABASE_VERSION = 1;
}
